{
  "name": "winstar-desktop",
  "version": "1.0.0",
  "description": "Winstar Desktop Application",
  "main": "src/main.js",
  "homepage": "./",
  "scripts": {
    "start": "electron .",
    "dev": "concurrently \"npm run react-start\" \"wait-on http://localhost:3000 && electron .\"",
    "react-start": "react-scripts start",
    "react-build": "react-scripts build",
    "build:win": "npm run react-build && electron-builder --win",
    "build:mac": "npm run react-build && electron-builder --mac",
    "build:linux": "npm run react-build && electron-builder --linux",
    "build": "npm run react-build && electron-builder -mwl"
  },
  "author": "Salim Amin",
  "license": "MIT",
  "dependencies": {
    "electron-squirrel-startup": "^1.1.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1"
  },
  "devDependencies": {
    "concurrently": "^8.2.0",
    "electron": "^latest",
    "electron-builder": "^24.6.4",
    "wait-on": "^7.0.1"
  },
  "build": {
    "appId": "com.winstar.app",
    "productName": "Winstar",
    "files": [
      "build/**/*",
      "src/main.js",
      "src/preload.js",
      "node_modules/**/*"
    ],
    "directories": {
      "buildResources": "assets"
    },
    "win": {
      "target": [
        {
          "target": "portable",
          "arch": [
            "x64"
          ]
        }
      ]
    },
    "nsis": {
      "oneClick": false,
      "allowToChangeInstallationDirectory": true,
      "createDesktopShortcut": true,
      "createStartMenuShortcut": true,
      "shortcutName": "Winstar"
    }
  },
  "eslintConfig": {
    "extends": [
      "react-app"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "production_strict": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
